### ISSUE TITLE
Error loading recipe xlfoodmod:strawberry_slushie

### ISSUE THREAD

**Issue by xadowtek** [OneLemonyBoi/XLFoodMod#3]
I don't know why, but when launch SMP server, throw me this error:
[00:04:56] [Worker-Main-13/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe xlfoodmod:strawberry_slushie
com.google.gson.JsonSyntaxException: Unknown item 'xlfoodmod:strawberry_slushiee'
        at net.minecraft.item.crafting.ShapedRecipe.func_222129_c(ShapedRecipe.java:262) ~[?:?] {re:classloading}
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_291] {}
        at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:261) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapelessRecipe$Serializer.func_199425_a_(ShapelessRecipe.java:86) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapelessRecipe$Serializer.func_199425_a_(ShapelessRecipe.java:76) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_291] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_291] {}
        
I Have: Forge 1.16.5-36.1.24 / Minecraft 1.16.5 / xlfoodmod-1.16.4-1.2.0 / lemonlib-1.3.6
NO more mods, clean map.

**Comment by xadowtek** [comment]
[debug.log](https://github.com/OneLemonyBoi/XLFoodMod/files/6587703/debug.log)
[latest.log](https://github.com/OneLemonyBoi/XLFoodMod/files/6587704/latest.log)
